/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0 		*/
/*  Created On : 21-Sept.-2016 11:25:04 p. m. 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0 ;

/* Drop Tables */

DROP TABLE IF EXISTS `Tipo de documento` CASCADE
;

DROP TABLE IF EXISTS `RespuestaPeticion` CASCADE
;

DROP TABLE IF EXISTS `PQR` CASCADE
;

DROP TABLE IF EXISTS `Opciones` CASCADE
;

DROP TABLE IF EXISTS `Municipios` CASCADE
;

DROP TABLE IF EXISTS `JAC` CASCADE
;

DROP TABLE IF EXISTS `Integrante` CASCADE
;

DROP TABLE IF EXISTS `Encuesta` CASCADE
;

DROP TABLE IF EXISTS `Documento` CASCADE
;

DROP TABLE IF EXISTS `Contenido` CASCADE
;

DROP TABLE IF EXISTS `Ciudadano` CASCADE
;

/* Create Tables */

CREATE TABLE `Tipo de documento`
(
	`COD` INTEGER NOT NULL AUTO_INCREMENT,
	`TIPO` VARCHAR(50) 	 NULL,
	`DESCRIPCION` VARCHAR(50) 	 NULL,
	CONSTRAINT `PK_Tipo de documento` PRIMARY KEY (`COD`)
)

;

CREATE TABLE `RespuestaPeticion`
(
	`IDRespuesta` INT NOT NULL AUTO_INCREMENT,
	`IDPeticion` INT 	 NULL,
	`Detalle` VARCHAR(50) 	 NULL,
	`Fecha` VARCHAR(50) 	 NULL,
	CONSTRAINT `PK_Table1` PRIMARY KEY (`IDRespuesta`)
)

;

CREATE TABLE `PQR`
(
	`ID` INT NOT NULL AUTO_INCREMENT,
	`CEDULA` INTEGER 	 NULL,
	`DESCRIPCION` VARCHAR(200) 	 NULL,
	`FECHA` VARCHAR(50)	 NULL,
	`ESTADO` VARCHAR(50) 	 NULL,
	`CORREO` VARCHAR(50) 	 NULL,
	CONSTRAINT `PK_Table1` PRIMARY KEY (`ID`)
)

;

CREATE TABLE `Opciones`
(
	`ID` INTEGER 	 NULL,
	`IDP` INTEGER 	 NULL,
	`OPCION` VARCHAR(50) 	 NULL,
	`VOTOS` INTEGER 	 NULL
)

;

CREATE TABLE `Municipios`
(
	`ID` INTEGER NOT NULL AUTO_INCREMENT,
	`Nombre` VARCHAR(50) 	 NULL,
	CONSTRAINT `PK_Municipios` PRIMARY KEY (`ID`)
)

;

CREATE TABLE `JAC`
(
	`cod` INTEGER NOT NULL AUTO_INCREMENT,
	`idMunicipio` INTEGER 	 NULL,
	`jurisdiccion` VARCHAR(50) 	 NULL,
	CONSTRAINT `PK_Table1` PRIMARY KEY (`cod`)
)

;

CREATE TABLE `Integrante`
(
	`Cedula` INTEGER 	 NULL,
	`cargo` VARCHAR(50) 	 NULL,
	`codjunta` INTEGER 	 NULL,
	`periodo` VARCHAR(50) 	 NULL
)

;

CREATE TABLE `Encuesta`
(
	`ID` INTEGER NOT NULL AUTO_INCREMENT,
	`PREGUNTA` VARCHAR(50) 	 NULL,
	CONSTRAINT `PK_Table1` PRIMARY KEY (`ID`)
)

;

CREATE TABLE `Documento`
(
	`ID` INTEGER NOT NULL AUTO_INCREMENT,
	`TIPO` INTEGER 	 NULL,
	`DESCRIPCION` VARCHAR(50) 	 NULL,
	`FECHA` VARCHAR(50) 	 NULL,
	`PALABRAS CLAVES` VARCHAR(50) 	 NULL,
	`CODJUNTA` INTEGER 	 NULL,
	`RUTA` VARCHAR(50) 	 NULL,
	`ESTADO` INTEGER 	 NULL,
	CONSTRAINT `PK_Table1` PRIMARY KEY (`ID`)
)

;

CREATE TABLE `Contenido`
(
	`ID` INT NOT NULL AUTO_INCREMENT,
	`TITULO` VARCHAR(50) 	 NULL,
	`INFORMACION` VARCHAR(200) 	 NULL,
	`RUTA` VARCHAR(50) 	 NULL,
	`Ubicacion` VARCHAR(50) 	 NULL,
	`Fecha creacion` VARCHAR(50) 	 NULL,
	`Fecha actualizacion` VARCHAR(50) 	 NULL,
	`Estado` VARCHAR(50) 	 NULL,
	CONSTRAINT `PK_Table1` PRIMARY KEY (`ID`)
)

;

CREATE TABLE `Ciudadano`
(
	`Cedula` INTEGER NOT NULL,
	`Nombre` VARCHAR(50) 	 NULL,
	`Edad` INTEGER 	 NULL,
	`Telefono` VARCHAR(50) 	 NULL,
	`Direccion` VARCHAR(50) 	 NULL,
	`Correo` VARCHAR(50) 	 NULL,
	CONSTRAINT `PK_Ciudadano` PRIMARY KEY (`Cedula`)
)

;

/* Create Indexes, Uniques, Checks */

ALTER TABLE `RespuestaPeticion` 
 ADD INDEX `IXFK_RespuestaPeticion_PQR` (`IDPeticion` ASC)
;

ALTER TABLE `PQR` 
 ADD INDEX `IXFK_PQR_Ciudadano` (`CEDULA` ASC)
;

ALTER TABLE `Opciones` 
 ADD INDEX `IXFK_Opciones_Encuesta` (`IDP` ASC)
;

ALTER TABLE `JAC` 
 ADD INDEX `IXFK_JAC_Municipios` (`idMunicipio` ASC)
;

ALTER TABLE `Integrante` 
 ADD INDEX `IXFK_Integrante_Ciudadano` (`Cedula` ASC)
;

ALTER TABLE `Integrante` 
 ADD INDEX `IXFK_Integrante_JAC` (`codjunta` ASC)
;

ALTER TABLE `Documento` 
 ADD INDEX `IXFK_Documento_JAC` (`CODJUNTA` ASC)
;

ALTER TABLE `Documento` 
 ADD INDEX `IXFK_Documento_Tipo de do01` (`TIPO` ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE `RespuestaPeticion` 
 ADD CONSTRAINT `FK_RespuestaPeticion_PQR`
	FOREIGN KEY (`IDPeticion`) REFERENCES `PQR` (`ID`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `PQR` 
 ADD CONSTRAINT `FK_PQR_Ciudadano`
	FOREIGN KEY (`CEDULA`) REFERENCES `Ciudadano` (`Cedula`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `Opciones` 
 ADD CONSTRAINT `FK_Opciones_Encuesta`
	FOREIGN KEY (`IDP`) REFERENCES `Encuesta` (`ID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `JAC` 
 ADD CONSTRAINT `FK_JAC_Municipios`
	FOREIGN KEY (`idMunicipio`) REFERENCES `Municipios` (`ID`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `Integrante` 
 ADD CONSTRAINT `FK_Integrante_Ciudadano`
	FOREIGN KEY (`Cedula`) REFERENCES `Ciudadano` (`Cedula`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `Integrante` 
 ADD CONSTRAINT `FK_Integrante_JAC`
	FOREIGN KEY (`codjunta`) REFERENCES `JAC` (`cod`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `Documento` 
 ADD CONSTRAINT `FK_Documento_JAC`
	FOREIGN KEY (`CODJUNTA`) REFERENCES `JAC` (`cod`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `Documento` 
 ADD CONSTRAINT `FK_Documento_Tipo de documento`
	FOREIGN KEY (`TIPO`) REFERENCES `Tipo de documento` (`COD`) ON DELETE No Action ON UPDATE No Action
;

SET FOREIGN_KEY_CHECKS=1 ;
